### ISSUE TITLE
Some clips are missing from VTuber's pages despite being correctly registered in the system

### ISSUE THREAD

**Issue by Type-kun** [RiceCakess/Holodex-old#10]
Polka's clips page at the moment:
![image](https://user-images.githubusercontent.com/3628092/97091268-25ab9d80-1654-11eb-8486-9e446d760990.png)

Searching for "polka" without selecting the tag:
![image](https://user-images.githubusercontent.com/3628092/97091309-7ae7af00-1654-11eb-897e-52b5cd6e44a3.png)

These 3 missing clips seem to have polka's tag correctly applied:
https://holodex.net/watch/1631549
https://holodex.net/watch/1627033
https://holodex.net/watch/1618635

Curiously, if you search by a tag popup, the clips will not be found either:
![image](https://user-images.githubusercontent.com/3628092/97091334-bc785a00-1654-11eb-8833-7bcd37960ddd.png)

**Comment by RiceCakess** [comment]
Thanks for the catch, I'll look into it

**Comment by RiceCakess** [comment]
Hello, I have pushed out an update that should fix this. Videos should be updated in the next 2 hours or so. Let me know if you see any other missing clips after that.

**Comment by Type-kun** [comment]
Seems fine so far, thanks for the fix
