### ISSUE TITLE
Non-vtuber stats/gains are broken

### ISSUE THREAD

**Issue by Type-kun** [RiceCakess/Holodex-old#11]
![image](https://user-images.githubusercontent.com/3628092/97161654-f0ac6180-179f-11eb-9d55-46952e863179.png)

**Comment by RiceCakess** [comment]
Thanks for reporting this. I think I know why but it's low priority for now.

**Comment by Type-kun** [comment]
Just a heads-up that all stats are broken now, VTubers as well, they are not updating since 10th.

**Comment by RiceCakess** [comment]
Oh what, hmm I'll take a look

**Comment by RiceCakess** [comment]
Vtuber stats should be fixed now, let me know if it's still stuck on the 10th. 

I'll keep this open for now, since the non vtuber stats issue is still there.

**Comment by RiceCakess** [comment]
Stats has been deprecated for now, we may revisit in the future
