### ISSUE TITLE
Feature request: modify "redirect mode" setting to still allow opening Holodex page on demand

### ISSUE THREAD

**Issue by Type-kun** [RiceCakess/Holodex-old#14]
Redirect mode is a great idea because most of the time I want the link to take me straight to the vid. However, sometimes I'd like to see the holodex video page instead, to check out metadata or related clips. Currently there seems to be no way to do that from videos list. 

How about splitting the links when the setting is on, so that thumbnail and title lead to YT while "X days ago" and "X clips" in the bottom lead to the holodex page, like this?

![image](https://user-images.githubusercontent.com/3628092/98982737-a23de780-2541-11eb-8dd5-8087f84dd124.png)

**Comment by RiceCakess** [comment]
Hmm, it should be doable, but they only issue I see is how to convey to users that clicking on those should open holodex.

The alternative is to have a setting that when clicking on the link, it opens youtube in new tab and at the same time it opens the holodex watch page in the background.

**Comment by Type-kun** [comment]
>Hmm, it should be doable, but they only issue I see is how to convey to users that clicking on those should open holodex.

Another option I see would be leaving all the links to lead to YT but adding a small Holodex icon somewhere under the video when redirect mode is enabled, and have that icon lead to Holodex. Then again, having "2 clips" lead to youtube when the mode is on also feels kinda counter-intuitive.

**Comment by RiceCakess** [comment]
Yea, you made a good point. I'll have clips redirect to the holodex page, not sure about the date though.

**Comment by RiceCakess** [comment]
Added in latest update
