### ISSUE TITLE
Live/Upcoming streams display

### ISSUE THREAD

**Issue by TMTenshi** [RiceCakess/Holodex-old#21]
Currently, the only streams displayed on the Live/Upcoming section is subaru's upcoming stream and the 2 streams from the official channel when holotools shows 3 livestreams and a dozen upcoming ones. The problem persists with different browsers and even on the ios phone.
![image](https://user-images.githubusercontent.com/76079174/102290875-809c9b00-3f07-11eb-842c-2d211c023fc7.png)

**Comment by RiceCakess** [comment]
Hey, thanks for the heads up. Something was misconfigured from our maintenance last night. 

It is now fixed, and things should up to date in a few minutes.

**Comment by TMTenshi** [comment]
Yeah no problem, thanks for the quick fix!
