### ISSUE TITLE
Saved videos list

### ISSUE THREAD

**Issue by RiceCakess** [RiceCakess/Holodex-old#4]
Allow users to save videos similar to Youtube's Watch Later. Allow for play back similar to playlists from said list.

**Comment by sphinxrave** [comment]
might need login capability to do this tbh, otherwise the list will be per-user. hmm.

**Comment by RiceCakess** [comment]
Working on it right now, thinking of saving to store and then exporting as YouTube playlist by passing all the video keys in the URL. 

I really want to do user accounts, since it would open up a lot of cool features, including push notifications. But I'm not super familiar with auth, so I've been putting it off.

**Comment by sphinxrave** [comment]
That would probably work yeah... you don't even need login capability, as you can just store the cookies in session and query Google for playlist info... but you might want a local cache =/

hmm...
