### ISSUE TITLE
Aki Rosenthal Incorrect Channel

### ISSUE THREAD

**Issue by DrQuantum101** [RiceCakess/Holodex-old#5]
Often attempts to pull videos and clips from the incorrect Aki Rosenthal Channel 

Incorrect Channel: https://www.youtube.com/channel/UCLbtM3JZfRTg8v2KGag-RMw

Correct Channel: https://www.youtube.com/channel/UCFTL

#
![image](https://user-images.githubusercontent.com/73178237/96592320-453e7100-12b6-11eb-88cf-a0e3ed0b93ff.png)

**Comment by RiceCakess** [comment]
Hello, that's actually her sub account that is now inactive. 

Here is her main account on Holodex

https://holodex.net/channel/32
