### ISSUE TITLE
Feature Request: Periodical refresh of Content pane for Home / Favorites

### ISSUE THREAD

**Issue by Arestris** [RiceCakess/Holodex-old#8]
I really like Holodex. Great page. Thanks for that.

What I noticed, if you use the page longer to see what's currently happening, it would be handy if the content area would periodically update with the running /current streams and the recently released videos.
In order not to burden mobile users more than necessary, you could make the whole thing configurable in the settings (another toggle to activate periodic refresh).
As time frame I think a refresh every two or even every five minutes would be sufficient, that would, I guess, also keep the load for the site manageable.

If this is not an option, it would at least be nice if you could press "Home" (or "Favorites") to trigger a manual reload. Currently nothing happens if you're already on "Home" (or "Favorites") and then click on the "Home" (or "Favorites") menu entry again.

**Comment by RiceCakess** [comment]
I'm planning on having an option to auto refresh the upcoming/live list. 

Moving between Home and Favorites should pull in fresh data if it's been more than 120 seconds.

**Comment by RiceCakess** [comment]
Notes for this planned feature:

- Query live api at every 15th minute, ex. 12:15pm, 12:30 pm, 12:45pm... (subject to change)
- Update results in the store state
- Sort favorites in the sidebar/channels page by live/upcoming status (red dot to the right of the name indicate currently live or countdown timer other wise)
- Linking the videolist to the store data should make the live channels reactive on Home page (meaning the cards will self update at every interval). 
-  Watch page should check channel mentions for any collab channels and have buttons to "change perspective" while live.

**Comment by RiceCakess** [comment]
Live videos section is refreshed every 5 minutes now.
