### ISSUE TITLE
Refresh page when clicking on corresponding button

### ISSUE THREAD

**Issue by nicolas-abril** [RiceCakess/Holodex-old#9]
On Youtube, clicking Home when I'm at Home, or Subscriptions when I'm at Subscriptions refreshes the page.

I think it would work well on Holodex as well.

**Comment by RiceCakess** [comment]
So technically when you move between the two pages, it will try to refresh the videos like Youtube, if there is new videos. There is an additional 120 second delay, so the mobile versions can't spam refreshes while tabbing back and forth. I can try shortening to 60 or 30 secs. 

Please let me know if you are having trouble getting it to refresh.

**Comment by nicolas-abril** [comment]
I just find it slightly annoying to tab out and the tab in again. Refreshing works fine

**Comment by RiceCakess** [comment]
Oh, I misunderstood your original question. I'll see what I can do about it.

**Comment by RiceCakess** [comment]
Added in latest update
